utene/testing/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from testing.views import TestCaseListView, TestCaseCreateView, \
    TestCaseUpdateView, TestCasesReportView, TestCaseDeleteView,\
    TestCasesReportDoView, TestPlanListView, TestPlanCreateView,\
    TestPlanUpdateView, TestPlanExecutionView, TestPlanExecutionCreateView


urlpatterns = patterns('testing.views',

    url(r'test_cases/$', login_required(TestCaseListView.as_view()), name='testcases'),
    url(r'test_case/create/$', login_required(TestCaseCreateView.as_view()), name='testcase_create'),
    url(r'test_case/update/(?P<pk>\d+)/$', login_required(TestCaseUpdateView.as_view()), name='testcase_update'),
    url(r'test_case/delete/(?P<pk>\d+)/$', login_required(TestCaseDeleteView.as_view()), name='testcase_delete'),
    
    url(r'testing_plan/$', login_required(TestPlanListView.as_view()), name='testingplan'),
    url(r'testing_plan/create/$', login_required(TestPlanCreateView.as_view()), name='testplan_create'),
    url(r'testing_plan/update/(?P<pk>\d+)/$', login_required(TestPlanUpdateView.as_view()), name='testplan_update'),

    url(r'test_cases_report/$', login_required(TestCasesReportView.as_view()), name='testcasesreports'),
    url(r'test_cases_report_do/$', login_required(TestCasesReportDoView.as_view()), name='testcasesreportsdo'),
    
    url(r'testing_plan_execution/(?P<plan_pk>\d+)/$', login_required(TestPlanExecutionView.as_view()), name='testingplanexecution'),
    url(r'testing_plan_executetestcase/(?P<plan_pk>\d+)/(?P<testcase_pk>\d+)/$', login_required(TestPlanExecutionCreateView.as_view()), name='testplan_executetestcase'),

)

utene/user/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from user.views import UserInfoUpdateView


urlpatterns = patterns('user.views',

    url(r'user/(?P<pk>\d+)/$', login_required(UserInfoUpdateView.as_view()), name='userinfo'),

)

utene/utene/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required

#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
    
    url(r'^$', login_required(RedirectView.as_view(url='/requirements/requirements/')), name='home'),
    url(r'^requirements/', include('requirements.urls', namespace='requirements')),
    url(r'^testing/', include('testing.urls', namespace='testing')),
    url(r'^user/', include('user.urls', namespace='user')),
    
    #url(r'^admin/', include(admin.site.urls)),
    (r'^i18n/', include('django.conf.urls.i18n')),
    
    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html'}, name='login'),

    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',
        {'template_name': 'logout.html'}, name='logout')

)

utene/testing/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse_lazy
from requirements.models import Requirement
import datetime
from django.conf.global_settings import AUTH_USER_MODEL


class TestCase(models.Model):
    
    EXECUTION_TYPES = (
        ('M', _('Manual')),
        ('A', _('Automated'))
    )
    
    TEST_CASE_TYPES = (
        ('U', _('Unit')),
        ('I', _('Integration')),
        ('S', _('Security')),
        ('G', _('System')),
        ('A', _('Acceptance')),
        ('C', _('Load'))
    )
    
    title = models.CharField(_('Title'), max_length=255)
    author = models.ForeignKey(User, verbose_name=_('Author'))
    objective = models.TextField(_('Objective'))
    test_case_type = models.CharField(_('Type'),
                                      max_length=1,
                                      choices=TEST_CASE_TYPES)
    requirement = models.ForeignKey(Requirement,
                                    verbose_name=_('Requirement'),
                                    related_name='test_cases')
    execution_type = models.CharField(verbose_name=_('Execution Type'),
                                      max_length=2,
                                      choices=EXECUTION_TYPES)
    estimated_execution_time = \
        models.PositiveIntegerField(_('Estimated Execution Time'))
    
    def __unicode__(self):
        return "%s - %s" % (self.id, self.title)
    
    def get_absolute_url(self):
        return reverse_lazy('testing:testcase_update',
                            kwargs={'pk': self.pk})
    
    def get_absolute_delete_url(self):
        return reverse_lazy('testing:testcase_delete',
                            kwargs={'pk': self.pk})


class TestCasePreCondition(models.Model):

    test_case = models.ForeignKey(TestCase, related_name='preconditions')
    description = models.CharField(verbose_name=_('Description'),
                                   max_length=255)
    
    def __unicode__(self):
        return self.description


class TestCasePostCondition(models.Model):

    test_case = models.ForeignKey(TestCase, related_name='postconditions')
    description = models.CharField(verbose_name=_('Description'),
                                   max_length=255)
    
    def __unicode__(self):
        return self.description


class TestCaseRevision(models.Model):

    test_case = models.ForeignKey(TestCase, related_name='revisions')
    user = models.ForeignKey(User, verbose_name=_('User'))
    description = models.CharField(_('Description'), max_length=255)
    date = models.DateTimeField(_('Date'), auto_now_add=True)


class TestCaseStep(models.Model):

    test_case = models.ForeignKey(TestCase, related_name='steps')
    step_number = models.PositiveSmallIntegerField(_('Step number'))
    step_action = models.TextField(_('Step action'))
    step_expected_result = models.TextField(_('Expected Result'))


class TestPlan(models.Model):

    name = models.CharField(_('Name'), max_length=255)
    start_date = models.DateField(_('Start Date'))
    end_date = models.DateField(_('End Date'))
    
    class Meta:
        ordering = ('-start_date', )
    
    def __unicode__(self):
        return u"%s - %s - %s" % (self.name, self.start_date, self.end_date)
    
    @property
    def active(self):
        today = datetime.date.today()
        return self.start_date <= today and self.end_date >= today


class TestPlanExecution(models.Model):

    TEST_CASE_EXECUTION_RESULT = (
        ('B', _('Blocked')),
        ('F', _('Fail')),
        ('I', _('Inconclusive')),
        ('P', _('Pass'))
    )

    test_plan = models.ForeignKey(TestPlan, verbose_name=_('Test Plan'))
    test_case = models.ForeignKey(TestCase, verbose_name=_('Test Case'))
    qa_resource = models.ForeignKey(AUTH_USER_MODEL, verbose_name=_('QA Resource'))
    date = models.DateTimeField(auto_now_add=True)
    result = models.CharField(max_length=1, choices=TEST_CASE_EXECUTION_RESULT, verbose_name=_('Result'))
    observations = models.TextField(null=True, blank=True, verbose_name=_('Observations'))

utene/testing/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.http.response import HttpResponse, HttpResponseRedirect
from django.template.context import RequestContext
from django.template.loader import render_to_string
from django.utils.translation import ugettext as _
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django_tables2.views import SingleTableView
from ho import pisa
from testing.forms import TestCasePreConditionFormSet, \
    TestCasePostConditionFormSet, TestCaseStepFormSet, TestCaseRevisionForm, \
    TestCaseForm, TestPlanExecutionForm
from testing.models import TestCase, TestPlan, TestPlanExecution
from testing.tables import TestCaseTable, TestPlanTable, \
    TestCasesForPlanExecutionTable
import StringIO
import cgi


class TestCaseListView(SingleTableView):
    model = TestCase
    table_class = TestCaseTable


class TestCaseCreateView(CreateView):
    model = TestCase
    form_class = TestCaseForm
    success_url = reverse_lazy("testing:testcases")
    
    def get_context_data(self, **kwargs):
        context = CreateView.get_context_data(self, **kwargs)
        context['preconditions_formset'] = TestCasePreConditionFormSet(
            self.request.POST or None,
            instance=self.model()
        )
        context['postconditions_formset'] = TestCasePostConditionFormSet(
            self.request.POST or None,
            instance=self.model()
        )
        context['steps_formset'] = TestCaseStepFormSet(
            self.request.POST or None,
            instance=self.model()
        )
        context['revision_form'] = TestCaseRevisionForm(
            self.request.POST or None
        )
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = self.model()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data()
        preconditions_formset = context['preconditions_formset']
        postconditions_formset = context['postconditions_formset']
        steps_formset = context['steps_formset']
        revision_form = context['revision_form']
        preconditions_formset.clean()
        if form.is_valid() and \
            preconditions_formset.is_valid() and \
            postconditions_formset.is_valid() and \
            steps_formset.is_valid() and \
            revision_form.is_valid():

            self.object = form.save(commit=False)
            self.object.author = self.request.user
            self.object.save()
            preconditions = preconditions_formset.save(commit=False)
            for p in preconditions:
                p.test_case = self.object
                p.save()
            postconditions = postconditions_formset.save(commit=False)
            for p in postconditions:
                p.test_case = self.object
                p.save()
            steps = steps_formset.save(commit=False)
            for s in steps:
                s.test_case = self.object
                s.save()
            revision = revision_form.save(commit=False)
            revision.test_case = self.object
            revision.user = self.request.user
            revision.save()
            messages.success(self.request, _('Test Case created'))
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.form_invalid(form)


class TestCaseUpdateView(UpdateView):
    model = TestCase
    form_class = TestCaseForm
    success_url = reverse_lazy("testing:testcases")
    
    def get_context_data(self, **kwargs):
        context = UpdateView.get_context_data(self, **kwargs)
        context['preconditions_formset'] = TestCasePreConditionFormSet(
            self.request.POST or None,
            instance=self.object
        )
        context['postconditions_formset'] = TestCasePostConditionFormSet(
            self.request.POST or None,
            instance=self.object
        )
        context['steps_formset'] = TestCaseStepFormSet(
            self.request.POST or None,
            instance=self.object
        )
        context['revision_form'] = TestCaseRevisionForm(
            self.request.POST or None
        )
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data()
        preconditions_formset = context['preconditions_formset']
        postconditions_formset = context['postconditions_formset']
        steps_formset = context['steps_formset']
        revision_form = context['revision_form']
        preconditions_formset.clean()
        if form.is_valid() and \
            preconditions_formset.is_valid() and \
            postconditions_formset.is_valid() and \
            steps_formset.is_valid() and \
            revision_form.is_valid():

            self.object = form.save()
            preconditions = preconditions_formset.save(commit=False)
            for p in preconditions:
                p.test_case = self.object
                p.save()
            postconditions = postconditions_formset.save(commit=False)
            for p in postconditions:
                p.test_case = self.object
                p.save()
            steps = steps_formset.save(commit=False)
            for s in steps:
                s.test_case = self.object
                s.save()
            revision = revision_form.save(commit=False)
            revision.test_case = self.object
            revision.user = self.request.user
            revision.save()
            messages.success(self.request, _('Test Case updated'))
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.form_invalid(form)


class TestCaseDeleteView(DeleteView):
    model = TestCase
    success_url = reverse_lazy("testing:testcases")


def _generate_pdf(html):
    #Function for generating the PDF file and return it using HttpResponse
    result = StringIO.StringIO()
    pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("UTF-8")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), mimetype='application/pdf')
    return HttpResponse(_('Error while creating the PDF file: %s' % cgi.escape(html)))
 
 
class TestCasesReportView(TemplateView):
    template_name = 'testing/test_cases_report_options.html'
    
    def get_context_data(self, **kwargs):
        c = TemplateView.get_context_data(self, **kwargs)
        c['report_types'] = (
            ('PDF', 'PDF'),
            ('HTML', 'HTML')
        )
        c['TEST_CASE_TYPES'] = TestCase.TEST_CASE_TYPES
        c['EXECUTION_TYPES'] = TestCase.EXECUTION_TYPES
        return c


class TestCasesReportDoView(TemplateView):
    template_name = 'testing/test_cases_report.html'

    def get(self, request, *args, **kwargs):
        #get values from POST
        report_type = request.GET.get('report_type')
        test_case_type = request.GET.get('test_case_type', None)
        execution_type = request.GET.get('execution_type', None)
        
        #Clean data
        if test_case_type == u"": test_case_type = None
        if execution_type == u"": execution_type = None
        
        #Get the query
        q = TestCase.objects
        if test_case_type:
            q = q.filter(test_case_type=test_case_type)
        if execution_type:
            q = q.filter(execution_type=execution_type)
        
        #Finally get the objects
        test_cases = q.all()

        if report_type == 'HTML':
            context = self.get_context_data(**kwargs)
            context['test_cases'] = test_cases
            return self.render_to_response(context) 
        elif report_type == 'PDF':
            data = dict(
                test_cases = test_cases,
                pagesize = 'A4',
            )
            html = render_to_string(
                self.template_name, data, context_instance=RequestContext(request))
            return _generate_pdf(html)


class TestPlanListView(SingleTableView):
    model = TestPlan
    table_class = TestPlanTable


class TestPlanCreateView(CreateView):
    model = TestPlan
    success_url = reverse_lazy("testing:testingplan")


class TestPlanUpdateView(UpdateView):
    model = TestPlan
    success_url = reverse_lazy("testing:testingplan")


class TestPlanExecutionView(SingleTableView):
    model = TestCase
    table_class = TestCasesForPlanExecutionTable
    template_name = 'testing/test_plan_execution.html'
    
    def get_context_data(self, **kwargs):
        c = SingleTableView.get_context_data(self, **kwargs)
        c['plan'] = TestPlan.objects.get(pk=self.kwargs.get("plan_pk"))
        return c


class TestPlanExecutionCreateView(CreateView):
    model = TestPlanExecution
    form_class = TestPlanExecutionForm
    
    def get_initial(self):
        initial = CreateView.get_initial(self)
        initial['test_plan'] = TestPlan.objects.get(pk=self.kwargs.get('plan_pk'))
        initial['test_case'] = TestCase.objects.get(pk=self.kwargs.get('testcase_pk'))
        initial['qa_resource'] = self.request.user
        return initial

    def get_success_url(self):
        return reverse_lazy("testing:testingplanexecution", kwargs={
            'plan_pk': self.kwargs.get("plan_pk")
        })
        return CreateView.get_success_url(self)

utene/testing/templates/testing/__test_plan_actions.html
{% load i18n %}
<ul>
	<li>
		<a href="{% url 'testing:testplan_update' record.pk %}">{% trans 'Modify' %}</a>
	</li>
	{% if record.active %}
	<li>
		<a href="{% url 'testing:testingplanexecution' record.pk %}">{% trans 'Execute test cases' %}</a>
	</li>
</ul>
{% endif %}

utene/testing/templates/testing/__test_plan_execution_actions.html
{% load i18n %}
<ul>
	<li>
		<a href="{% url 'testing:testplan_executetestcase' plan.pk record.pk %}">{% trans 'Execute Test Case' %}</a>
	</li>
</ul>

utene/testing/templates/testing/__test_plan_execution_previous_results.html
{% load i18n %}
{% load testing_tags %}

{% testcase_previous_results plan.pk record.pk as previous %}
{% if previous %}
<table class='table table-bordered'>
	<tbody>
		{% regroup previous by get_result_display as previous_list %}
		{% for p in previous_list %}
		<tr>
			<td>{{ p.grouper }}</td>
			<td>{{ p.list|length }}</td>
		</tr>
		{% endfor %}
	</tbody>
	<tfoot>
		<tr>
			<th>{% trans "Executions" %}</th>
			<th>{{ previous|length }}</th>
		</tr>
	</tfoot>
</table>
{% else %}
{% trans "There are not executions yet for this plan" %}
{% endif %}

utene/testing/templates/testing/test_cases_report.html
{% extends 'base.html' %}
{% load i18n %}
{% load user_tags %}

{% block document_title %}{{ block.super }} - {% trans 'Test Cases Report' %}{% endblock %}

{% block nav %}{% endblock %}

{% block content %}
<style type="text/css">
table.gridtable {
	font-size:11px;
	color:#333333;
	border-width: 1px;
	border-color: #666666;
	border-collapse: collapse;
}
table.gridtable th {
	border-width: 1px;
	padding: 3px;
	border-style: solid;
	border-color: #666666;
	background-color: #dedede;
}
table.gridtable td {
	border-width: 1px;
	padding: 3px;
	border-style: solid;
	border-color: #666666;
	background-color: #ffffff;
}
</style>
{% for tc in test_cases %}
<table class='gridtable'>
	<tbody>
		<tr>
			<td colspan="2"><h2>[{{ tc.get_test_case_type_display }}] {{ tc }}</h2></td>
		</tr>
		<tr>
			<td width="20%">{% trans 'Author' %}</td>
			<td width="80%">{% user_display_name tc.author %}</td>
		</tr>
		<tr>
			<td>{% trans 'Objective' %}</td>
			<td>{{ tc.objective }}</td>
		</tr>
		<tr>
			<td>{% trans 'Requirement' %}</td>
			<td>{{ tc.requirement }}</td>
		</tr>
		<tr>
			<td>{% trans 'Pre-Conditions' %}</td>
			<td>
				<ul>
					{% for p in tc.preconditions.all %}
					<li>{{ p }}</li>
					{% endfor %}
				</ul>
			</td>
		</tr>
		<tr>
			<td>{% trans 'Actions' %}</td>
			<td>
				<table>
					<thead>
						<tr>
							<th width="10%">{% trans 'Step Number' %}</th>
							<th>{% trans 'Action' %}</th>
							<th>{% trans 'Expected Result' %}</th>
						</tr>
					</thead>
					<tbody>
						{% for s in tc.steps.all %}
						<tr>
							<td>{{ s.step_number }}</td>
							<td>{{ s.step_action }}</td>
							<td>{{ s.step_expected_result }}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</td>
		</tr>
		<tr>
			<td>{% trans 'Execution type' %}</td>
			<td>{{ tc.get_execution_type_display }}</td>
		</tr>
		<tr>
			<td>{% trans 'Post-Conditions' %}</td>
			<td>
				<ul>
					{% for p in tc.postconditions.all %}
					<li>{{ p }}</li>
					{% endfor %}
				</ul>
			</td>
		</tr>
		<tr>
			<td>{% trans 'Revisions' %}</td>
			<td>
				<table>
					<thead>
						<tr>
							<th width="20%">{% trans 'User' %}</th>
							<th>{% trans 'Date' %}</th>
							<th>{% trans 'Description' %}</th>
						</tr>
					</thead>
					<tbody>
						{% for revision in tc.revisions.all %}
						<tr>
							<td>{% user_display_name revision.user %}</td>
							<td>{{ revision.date }}</td>
							<td>{{ revision.description }}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</td>
		</tr>
		<tr>
			<td>{% trans 'Estimated execution type' %}</td>
			<td>{{ tc.estimated_execution_time }}</td>
		</tr>
		<tr>
			<td>{% trans 'Status' %}</td>
			<td></td>
		</tr>
	</tbody>
</table>
<pdf:nextpage />
{% endfor %}
{% endblock %}

utene/testing/templates/testing/test_cases_report_options.html
{% extends '__form.html' %}
{% load i18n %}

{% block title %}{% trans 'Test Cases Report Options' %}{% endblock %}

{% block content %}
<form method="get" action="{% url 'testing:testcasesreportsdo' %}" target="_blank">
	{% csrf_token %}
	<div class="row">
		<div class="span12">
			<h3>{% trans 'Report Type' %}</h3>
			<select name="report_type">
				{% for t in report_types %}
				<option value="{{ t.0 }}">{{ t.1 }}</option>
				{% endfor %}
			</select>
		</div>
	</div>
	<div class="row">
		<div class="span12">
			<h3>{% trans 'Test Case Type' %}</h3>
			<select name="test_case_type">
				<option value="">--</option>
				{% for t in TEST_CASE_TYPES %}
				<option value="{{ t.0 }}">{{ t.1 }}</option>
				{% endfor %}
			</select>
		</div>
	</div>
	<div class="row">
		<div class="span12">
			<h3>{% trans 'Execution Type' %}</h3>
			<select name="execution_type">
				<option value="">--</option>
				{% for t in EXECUTION_TYPES %}
				<option value="{{ t.0 }}">{{ t.1 }}</option>
				{% endfor %}
			</select>
		</div>
	</div>
	<input type="submit" id="submit" />
</form>
{% endblock %}

utene/testing/templates/testing/test_plan_execution.html
{% extends '__list_table.html' %}
{% load i18n %}

{% block title %}{% trans "Test Plan Execution" %}{% endblock %}

{% block subtitle %}{{ plan }}{% endblock %}

utene/testing/templates/testing/testcase_form.html
{% extends '__form.html' %}
{% load i18n %}
{% load widget_tweaks %}
{% load user_tags %}

{% block extra_js %}
{{ block.super }}
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.flexibleArea.js"></script>
<script>
	$(document).ready(function(){
		$("textarea").flexible();
		
		$('#preconditions tbody tr').formset({
			prefix: '{{ preconditions_formset.prefix }}',
			addText: '{% trans "add another" %}',
			deleteText: '{% trans "remove" %}'
		});
		
		$('#postconditions tbody tr').formset({
			prefix: '{{ postconditions_formset.prefix }}',
			addText: '{% trans "add another" %}',
			deleteText: '{% trans "remove" %}'
		});
		
		$('#steps tbody tr').formset({
			prefix: '{{ steps_formset.prefix }}',
			addText: '{% trans "add another" %}',
			deleteText: '{% trans "remove" %}'
		});
		
		$('#correctiveactions tbody tr').formset({
			prefix: '{{ correctiveactions_formset.prefix }}',
			addText: '{% trans "add another" %}',
			deleteText: '{% trans "remove" %}'
		});

	});
</script>
{% endblock %}

{% block title_entity %}{% trans 'Test Case' %}{% endblock %}

{% block content %}
<form method="post" action="{% block action %}{% endblock %}">
	{% csrf_token %}
	<div class="row">
		<div class="span4">
			<h3>{% trans "General Information" %}</h3>
			{{ form.as_p }}
		</div>
		<div class="span8">
			<h3>{% trans "Pre-Conditions" %}</h3>
			<div>
				{{ preconditions_formset.management_form }}
				{{ preconditions_formset.non_form_errors }}
				<table id="preconditions" class='table table-condensed'>
					<thead>
						{% with preconditions_formset.forms|first as pc %}
						<tr>
							<td>{{ pc.description.label }}</td>
							<td>{{ pc.DELETE.label }}</td>
						</tr>
						{% endwith %}
					</thead>
					<tbody>
						{% for subform in preconditions_formset.forms %}
						<tr>
							<td>{% render_field subform.description class+='span6' %}{{ subform.description.errors }}</td>
							<td>
								{{ subform.DELETE }}{{ subform.DELETE.errors }}
								{% for h in subform.hidden_fields %}
								{{ h }}
								{% endfor %}
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<h3>{% trans "Post-Conditions" %}</h3>
			<div>
				{{ postconditions_formset.management_form }}
				<table id="postconditions" class='table table-condensed'>
					<thead>
						{% with postconditions_formset.forms|first as pc %}
						<tr>
							<td>{{ pc.description.label }}</td>
							<td>{{ pc.DELETE.label }}</td>
						</tr>
						{% endwith %}
					</thead>
					<tbody>
						{% for subform in postconditions_formset.forms %}
						<tr>
							<td>{% render_field subform.description class+='span6' %}{{ subform.description.errors }}</td>
							<td>
								{{ subform.DELETE }}{{ subform.DELETE.errors }}
								{% for h in subform.hidden_fields %}
								{{ h }}
								{% endfor %}
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<h3>{% trans "Steps" %}</h3>
			<div>
				{{ steps_formset.management_form }}
				<table id="steps" class='table table-condensed'>
					<thead>
						{% with steps_formset.forms|first as pc %}
						<tr>
							<td>{{ pc.step_number.label }}</td>
							<td>{{ pc.step_action.label }}</td>
							<td>{{ pc.step_expected_result.label }}</td>
							<td>{{ pc.DELETE.label }}</td>
						</tr>
						{% endwith %}
					</thead>
					<tbody>
						{% for subform in steps_formset.forms %}
						<tr>
							<td>{% render_field subform.step_number class+='span1' %}{{ subform.step_number.errors }}</td>
							<td>{% render_field subform.step_action class+='span3' rows=3 %}{{ subform.step_action.errors }}</td>
							<td>{% render_field subform.step_expected_result class+='span3' rows=3 %}{{ subform.step_expected_result.errors }}</td>
							<td>
								{{ subform.DELETE }}{{ subform.DELETE.errors }}
								{% for h in subform.hidden_fields %}
								{{ h }}
								{% endfor %}
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<h3>{% trans "Revisions" %}</h3>
			<div>
				<table class="table table-condensed">
					<thead>
						<tr>
							<th>{% trans 'User' %}</th>
							<th>{% trans 'Date' %}</th>
							<th>{% trans 'Description' %}</th>
						</tr>
					</thead>
					<tbody>
						{% for revision in form.instance.revisions.all %}
						<tr>
							<td>{% user_display_name revision.user %}</td>
							<td>{{ revision.date }}</td>
							<td>{{ revision.description }}</td>
						</tr>
						{% endfor %}
					</tbody>
					<tfoot>
						<tr>
							<td colspan=3>&nbsp;</td>
						</tr>
					</tfoot>
				</table>
				{{ revision_form.description.label }} {% render_field revision_form.description class+='span5' %}{{ revision_form.description.errors }}
				{% for h in revision_form.hidden_fields %}
				{{ h }}
				{% endfor %}
			</div>
		</div>
	</div>
	<input type="submit" id="submit" />
</form>
{% endblock %}

utene/testing/templates/testing/testcase_list.html
{% extends '__list_table.html' %}
{% load i18n %}

{% block title_entities %}{% trans "Test Cases" %}{% endblock %}

{% block url_new %}{% url 'testing:testcase_create' %}{% endblock %}

utene/testing/templates/testing/testplan_form.html
{% extends '__form.html' %}
{% load i18n %}

{% block title_entity %}{% trans 'Testing Plan' %}{% endblock %}

{% block content %}
{{ block.super }}
<script>
	$(function() {
		$("#id_start_date,#id_end_date").datepicker({
			'dateFormat': 'dd/mm/yy'
		});
	}); 
</script>
{% endblock %}

utene/testing/templates/testing/testplan_list.html
{% extends '__list_table.html' %}
{% load i18n %}

{% block title_entities %}{% trans "Testing Plans" %}{% endblock %}

{% block url_new %}{% url 'testing:testplan_create' %}{% endblock %}

utene/testing/templates/testing/testplanexecution_form.html
{% extends '__form.html' %}
{% load i18n %}

{% block title_entity %}{% trans 'Test Case Execution' %}{% endblock %}