testing_plan/testing/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from testing.views import TestCaseListView, TestCaseCreateView, \
    TestCaseUpdateView, TestCasesReportView, TestCaseDeleteView,\
    TestCaseDetailView, TestCaseStateDetailView, TestCaseStateCreateView,\
    TestCaseStateDeleteView, TestCaseStateUpdateView


urlpatterns = patterns('testing.views',

    url(r'test_cases/$', login_required(TestCaseListView.as_view()), name='testcases'),
    url(r'test_case/create/$', login_required(TestCaseCreateView.as_view()), name='testcase_create'),
    url(r'test_case/view/(?P<pk>\d+)/$', login_required(TestCaseDetailView.as_view()), name='testcase_view'),
    url(r'test_case/update/(?P<pk>\d+)/$', login_required(TestCaseUpdateView.as_view()), name='testcase_update'),
    url(r'test_case/delete/(?P<pk>\d+)/$', login_required(TestCaseDeleteView.as_view()), name='testcase_delete'),

    url(r'test_cases_report/$', login_required(TestCasesReportView.as_view()), name='testcasesreports'),
    
    url(r'test_case_state/create/(?P<testcase_pk>\d+)/$', login_required(TestCaseStateCreateView.as_view()), name='testcasestate_create'),
    url(r'test_case_state/view/(?P<pk>\d+)/$', login_required(TestCaseStateDetailView.as_view()), name='testcasestate_detail'),
    url(r'test_case_state/update/(?P<pk>\d+)/$', login_required(TestCaseStateUpdateView.as_view()), name='testcasestate_update'),
    url(r'test_case_state/delete/(?P<pk>\d+)/$', login_required(TestCaseStateDeleteView.as_view()), name='testcasestate_delete'),

)

testing_plan/testing/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse_lazy
from requirements.models import Requirement


class TestCase(models.Model):
    
    EXECUTION_TYPES = (
        ('M', _('Manual')),
        ('A', _('Automated'))
    )
    
    TEST_CASE_TYPES = (
        ('U', _('Unit')),
        ('I', _('Integration')),
        ('S', _('Security')),
        ('G', _('System')),
        ('A', _('Acceptance')),
        ('C', _('Load'))
    )
    
    title = models.CharField(_('Title'), max_length=255)
    author = models.ForeignKey(User, verbose_name=_('Author'))
    objective = models.TextField(_('Objective'))
    test_case_type = models.CharField(_('Type'),
                                      max_length=1, 
                                      choices=TEST_CASE_TYPES)
    requirement = models.ForeignKey(Requirement, 
                                    verbose_name=_('Requirement'),
                                    related_name='test_cases')
    execution_type = models.CharField(verbose_name=_('Execution Type'),
                                      max_length=2,
                                      choices=EXECUTION_TYPES)
    estimated_execution_time = \
        models.PositiveIntegerField(_('Estimated Execution Time'))
    
    def __unicode__(self):
        return "%s - %s" % (self.id, self.title)
    
    def get_absolute_url_detail(self):
        return reverse_lazy('testing:testcase_view', 
                            kwargs={'pk': self.pk})
    
    def get_absolute_url(self):
        return reverse_lazy('testing:testcase_update', 
                            kwargs={'pk': self.pk})
    
    def get_absolute_delete_url(self):
        return reverse_lazy('testing:testcase_delete', 
                            kwargs={'pk': self.pk})


class TestCasePreCondition(models.Model):

    test_case = models.ForeignKey(TestCase, related_name='preconditions')
    description = models.CharField(verbose_name=_('Description'), 
                                   max_length=255)
    
    def __unicode__(self):
        return self.description


class TestCasePostCondition(models.Model):

    test_case = models.ForeignKey(TestCase, related_name='postconditions')
    description = models.CharField(verbose_name=_('Description'), 
                                   max_length=255)
    
    def __unicode__(self):
        return self.description


class TestCaseRevision(models.Model):

    test_case = models.ForeignKey(TestCase, related_name='revisions')
    user = models.ForeignKey(User, verbose_name=_('User'))
    description = models.CharField(_('Description'), max_length=255)
    date = models.DateTimeField(_('Date'), auto_now_add=True)


class TestCaseStep(models.Model):

    test_case = models.ForeignKey(TestCase, related_name='steps')
    step_number = models.PositiveSmallIntegerField(_('Step number'))
    step_action = models.TextField(_('Step action'))
    step_expected_result = models.TextField(_('Expected Result'))

    class Meta:
        ordering = ['step_number', ]


class TestCaseState(models.Model):
    
    STATES = (
        ("0", _("No Errors")),
        ("1", _("Crash/Data Loss")),
        ("2", _("Major Problem")),
        ("3", _("Minor Problem")),
        ("4", _("Cosmetic")),
    )
    
    test_case = models.ForeignKey(TestCase, related_name='states')
    state = models.CharField(_('State'), max_length=1, choices=STATES)
    description = models.TextField(_('Description'))

    date = models.DateTimeField(_('Date'), auto_now_add=True)
    user = models.ForeignKey(User, verbose_name=_('User'))

    completed = models.BooleanField(default=False, verbose_name=_('Completed'))
    completed_by = models.ForeignKey(User, verbose_name=_('Completed By'), related_name='states_completed', null=True, blank=True)
    corrective_action = models.TextField(_('Corrective Action'), null=True, blank=True)

    verified = models.BooleanField(default=False, verbose_name=_('Verified'))
    verified_by = models.ForeignKey(User, verbose_name=_('Verified By'), related_name='states_verified', null=True, blank=True)

testing_plan/testing/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from testing.models import TestCasePreCondition, TestCase, TestCasePostCondition, \
    TestCaseStep, TestCaseRevision, TestCaseState


TestCasePreConditionFormSet = \
    inlineformset_factory(TestCase, TestCasePreCondition)


TestCasePostConditionFormSet = \
    inlineformset_factory(TestCase, TestCasePostCondition)


TestCaseStepFormSet = \
    inlineformset_factory(TestCase, TestCaseStep)


# TestCaseCorrectiveActionFormSet = \
#     inlineformset_factory(TestCase, TestCaseCorrectiveAction)


class TestCaseRevisionForm(forms.ModelForm):

    class Meta:
        model = TestCaseRevision
        exclude = ('test_case', 'user',)


class TestCaseForm(forms.ModelForm):
    
    class Meta:
        model = TestCase
        exclude = ('author', )


class TestCaseStateForm(forms.ModelForm):
    
    class Meta:
        model = TestCaseState
        exclude = ('test_case', 'user', )

testing_plan/testing/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.http.response import HttpResponse, HttpResponseRedirect
from django.template.context import RequestContext
from django.template.loader import render_to_string
from django.utils.translation import ugettext as _
from django.views.generic.base import View, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django_tables2.views import SingleTableView
from ho import pisa
from testing.forms import TestCasePreConditionFormSet, \
    TestCasePostConditionFormSet, TestCaseStepFormSet, TestCaseRevisionForm, \
    TestCaseForm, TestCaseStateForm
from testing.models import TestCase, TestCaseState
from testing.tables import TestCaseTable
import StringIO
import cgi
from django.views.generic.detail import DetailView
#from relatorio.templates.opendocument import Template
#from django.conf import settings
#import os
#from django.shortcuts import render_to_response


class TestCaseListView(SingleTableView):
    model = TestCase
    table_class = TestCaseTable


class TestCaseDetailView(DetailView):
    model = TestCase


class TestCaseCreateView(CreateView):
    model = TestCase
    form_class = TestCaseForm
    success_url = reverse_lazy("testing:testcases")
    
    def get_context_data(self, **kwargs):
        context = CreateView.get_context_data(self, **kwargs)
        context['preconditions_formset'] = TestCasePreConditionFormSet(
            self.request.POST or None,
            instance=self.model()
        )
        context['postconditions_formset'] = TestCasePostConditionFormSet(
            self.request.POST or None,
            instance=self.model()
        )
        context['steps_formset'] = TestCaseStepFormSet(
            self.request.POST or None,
            instance=self.model()
        )
        context['revision_form'] = TestCaseRevisionForm(
            self.request.POST or None
        )
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = self.model()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data()
        preconditions_formset = context['preconditions_formset']
        postconditions_formset = context['postconditions_formset']
        steps_formset = context['steps_formset']
        revision_form = context['revision_form']
        preconditions_formset.clean()
        if form.is_valid() and \
            preconditions_formset.is_valid() and \
            postconditions_formset.is_valid() and \
            steps_formset.is_valid() and \
            revision_form.is_valid():

            self.object = form.save(commit=False)
            self.object.author = self.request.user
            self.object.save()
            preconditions = preconditions_formset.save(commit=False)
            for p in preconditions:
                p.test_case = self.object
                p.save()
            postconditions = postconditions_formset.save(commit=False)
            for p in postconditions:
                p.test_case = self.object
                p.save()
            steps = steps_formset.save(commit=False)
            for s in steps:
                s.test_case = self.object
                s.save()
            revision = revision_form.save(commit=False)
            revision.test_case = self.object
            revision.user = self.request.user
            revision.save()
            messages.success(self.request, _('Test Case created'))
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.form_invalid(form)


class TestCaseUpdateView(UpdateView):
    model = TestCase
    form_class = TestCaseForm
    success_url = reverse_lazy("testing:testcases")
    
    def get_context_data(self, **kwargs):
        context = UpdateView.get_context_data(self, **kwargs)
        context['preconditions_formset'] = TestCasePreConditionFormSet(
            self.request.POST or None,
            instance=self.object
        )
        context['postconditions_formset'] = TestCasePostConditionFormSet(
            self.request.POST or None,
            instance=self.object
        )
        context['steps_formset'] = TestCaseStepFormSet(
            self.request.POST or None,
            instance=self.object
        )
        context['revision_form'] = TestCaseRevisionForm(
            self.request.POST or None
        )
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data()
        preconditions_formset = context['preconditions_formset']
        postconditions_formset = context['postconditions_formset']
        steps_formset = context['steps_formset']
        revision_form = context['revision_form']
        preconditions_formset.clean()
        if form.is_valid() and \
            preconditions_formset.is_valid() and \
            postconditions_formset.is_valid() and \
            steps_formset.is_valid() and \
            revision_form.is_valid():

            self.object = form.save()
            preconditions = preconditions_formset.save(commit=False)
            for p in preconditions:
                p.test_case = self.object
                p.save()
            postconditions = postconditions_formset.save(commit=False)
            for p in postconditions:
                p.test_case = self.object
                p.save()
            steps = steps_formset.save(commit=False)
            for s in steps:
                s.test_case = self.object
                s.save()
            revision = revision_form.save(commit=False)
            revision.test_case = self.object
            revision.user = self.request.user
            revision.save()
            messages.success(self.request, _('Test Case updated'))
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.form_invalid(form)


class TestCaseDeleteView(DeleteView):
    model = TestCase
    success_url = reverse_lazy("testing:testcases")


def _generate_pdf(html):
    #Function for generating the PDF file and return it using HttpResponse
    result = StringIO.StringIO()
    pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("UTF-8")), result, encoding='UTF-8')
    if not pdf.err:
        return HttpResponse(result.getvalue(), mimetype='application/pdf')
    return HttpResponse(_('Error while creating the PDF file: %s' % cgi.escape(html)))
 
 
class TestCasesReportView(TemplateView):
    template_name = 'testing/test_cases_report_options.html'
    
    def get_context_data(self, **kwargs):
        c = TemplateView.get_context_data(self, **kwargs)
        c['report_types'] = (
            ('PDF', 'PDF'),
            ('HTML', 'HTML')
        )
        c['TEST_CASE_TYPES'] = TestCase.TEST_CASE_TYPES
        c['EXECUTION_TYPES'] = TestCase.EXECUTION_TYPES
        return c
    
    def post(self, request, *args, **kwargs):
        #get values from POST
        report_type = request.POST.get('report_type')
        test_case_type = request.POST.get('test_case_type', None)
        execution_type = request.POST.get('execution_type', None)
        only_with_states = request.POST.get('only_with_states', None)
        show_execution_results = request.POST.get('show_execution_results', None)
        
        #Clean data
        if test_case_type == u"": test_case_type = None
        if execution_type == u"": execution_type = None
        
        #Change the template_name value for the real report template
        self.template_name = 'testing/test_cases_report.html'
        
        #Get the query
        q = TestCase.objects
        if test_case_type:
            q = q.filter(test_case_type=test_case_type)
        if execution_type:
            q = q.filter(execution_type=execution_type)
        if only_with_states:
            q = q.filter(states__isnull=False)
        
        #Finally get the objects
        test_cases = q.all()
        
        if report_type == 'HTML':
            context = self.get_context_data(**kwargs)
            context['show_execution_results'] = show_execution_results
            context['test_cases'] = test_cases
            return self.render_to_response(context) 
        elif report_type == 'PDF':
            data = dict(
                test_cases = test_cases,
                show_execution_results = show_execution_results,
                pagesize = 'A4',
            )
            html = render_to_string(
                self.template_name, data, context_instance=RequestContext(request))
            return _generate_pdf(html)


# class TestCasesReportView(View):
#     
#     def get(self, request, *args, **kwargs):
#         test_cases = TestCase.objects.all().values()
#         print test_cases
#         templateFilePath = os.path.join(settings.PROJECT_PATH, 'testing', 'reports', 'testcases_skeleton.odt')
#         report = Template(source=open(templateFilePath,'r'),
#                           filepath=templateFilePath)
#         response = HttpResponse(
#             report.generate(test_cases=test_cases).render().getvalue(), 
#             mimetype='application/pdf')
#         response['Content-Disposition'] = 'attachment; filename="TestCasesReport.pdf"'
#         return response


class TestCaseStateCreateView(CreateView):
    model = TestCaseState
    form_class = TestCaseStateForm
    
    def get_success_url(self):
        return reverse_lazy("testing:testcase_view", kwargs={'pk': self.kwargs['testcase_pk']})
    
    def post(self, request, *args, **kwargs):
        self.object = self.model()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        
        if form.is_valid():

            self.object = form.save(commit=False)
            self.object.user = self.request.user

testing_plan/testing/templates/testing/__testcase_detail.html
{% load i18n %}
{% load user_tags %}
<table class='{{ table_class }}'>
	<tbody>
		<tr>
			<td colspan="2"><h2>[{{ tc.get_test_case_type_display }}] {{ tc }}</h2></td>
		</tr>
		<tr>
			<td width="20%">{% trans 'Author' %}</td>
			<td width="80%">{% user_display_name tc.author %}</td>
		</tr>
		<tr>
			<td>{% trans 'Objective' %}</td>
			<td>{{ tc.objective }}</td>
		</tr>
		<tr>
			<td>{% trans 'Requirement' %}</td>
			<td>{{ tc.requirement }}</td>
		</tr>
		<tr>
			<td>{% trans 'Pre-Conditions' %}</td>
			<td>
				<ul>
					{% for p in tc.preconditions.all %}
					<li>{{ p }}</li>
					{% endfor %}
				</ul>
			</td>
		</tr>
		<tr>
			<td>{% trans 'Actions' %}</td>
			<td>
				<table class="{{ subtable_class }}">
					<thead>
						<tr>
							<th width="10%">{% trans 'Step Number' %}</th>
							<th>{% trans 'Action' %}</th>
							<th>{% trans 'Expected Result' %}</th>
						</tr>
					</thead>
					<tbody>
						{% for s in tc.steps.all %}
						<tr>
							<td>{{ s.step_number }}</td>
							<td>{{ s.step_action }}</td>
							<td>{{ s.step_expected_result }}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</td>
		</tr>
		<tr>
			<td>{% trans 'Execution type' %}</td>
			<td>{{ tc.get_execution_type_display }}</td>
		</tr>
		<tr>
			<td>{% trans 'Post-Conditions' %}</td>
			<td>
				<ul>
					{% for p in tc.postconditions.all %}
					<li>{{ p }}</li>
					{% endfor %}
				</ul>
			</td>
		</tr>
		<tr>
			<td>{% trans 'Revisions' %}</td>
			<td>
				<table class="{{ subtable_class }}">
					<thead>
						<tr>
							<th width="20%">{% trans 'User' %}</th>
							<th>{% trans 'Date' %}</th>
							<th>{% trans 'Description' %}</th>
						</tr>
					</thead>
					<tbody>
						{% for revision in tc.revisions.all %}
						<tr>
							<td>{% user_display_name revision.user %}</td>
							<td>{{ revision.date }}</td>
							<td>{{ revision.description }}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</td>
		</tr>
		<tr>
			<td>{% trans 'Estimated execution type' %}</td>
			<td>{{ tc.estimated_execution_time }}</td>
		</tr>
		{% if show_execution_results %}
		<tr>
			<td>{% trans 'States' %}</td>
			<td>
				{% with tc as record %}
					{% include 'testing/__testcase_states.html' with actions=actions %}
				{% endwith %}
			</td>
		</tr>
		{% endif %}
	</tbody>
</table>

testing_plan/testing/templates/testing/__testcase_states.html
{% load i18n %}
{% load user_tags %}

{% with record.states.all as states %}
<table class='{{ table_class }}'>
	<thead>
		<tr>
			<th>{% trans "State" %}</th>
			<th>{% trans "Date" %}</th>
			<th>{% trans "Description" %}</th>
			<th>{% trans "User" %}</th>
			<th>{% trans "Completed" %}</th>
			<th>{% trans "Corrective Action" %}</th>
			<th>{% trans "Verified" %}</th>
			{% if actions %}
			<th>&nbsp;</th>
			{% endif %}
		</tr>
	</thead>
	<tbody>
		{% for s in states %}
		<tr>
			<td>{{ s.get_state_display }}</td>
			<td>{{ s.date }}</td>
			<td>{{ s.description }}</td>
			<td>{% user_display_name s.user %}</td>
			<td>
				{% if s.completed %}
					{% trans "Yes, by" %} {{ s.completed_by }}
				{% else %}
					{% trans "No" %}
				{% endif %}
			</td>
			<td>{{ s.corrective_action|default_if_none:"" }}</td>
			<td>
				{% if s.verified %}
					{% trans "Yes, by" %} {{ s.verified_by }}
				{% else %}
					{% trans "No" %}
				{% endif %}
			</td>
			{% if actions %}
			<td>
				<div class="btn-group">
					<a href="{% url 'testing:testcasestate_update' s.pk %}" class="btn">+</a>
					<a href="{% url 'testing:testcasestate_delete' s.pk %}" class="btn">x</a>
				</div>
			</td>
			{% endif %}
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endwith %}

testing_plan/testing/templates/testing/__testcasestates_summary.html
{% load i18n %}
{% load testing_tags %}

{% testcasestates_summary as results %}
<table class="table table-bordered">
	<thead>
		<tr>
			<th>{% trans "State" %}</th>
			<th>{% trans "Total" %}</th>
			<th>{% trans "Completed" %}</th>
			<th>{% trans "Verified" %}</th>
		</tr>
	</thead>
	<tbody>
		{% for result in results %}
		<tr>
			<td>{{ result.state }}</td>
			<td>{{ result.total }}</td>
			<td>{{ result.completed }}</td>
			<td>{{ result.verified }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

testing_plan/testing/templates/testing/requirement_form.html
{% extends '__form.html' %}
{% load i18n %}

{% block title_entity %}{% trans 'Requirement' %}{% endblock %}

testing_plan/testing/templates/testing/requirement_list.html
{% extends '__list_table.html' %}
{% load i18n %}

{% block title_entities %}{% trans "Requirements" %}{% endblock %}


{% block url_new %}{% url 'testing:requirement_create' %}{% endblock %}

testing_plan/testing/templates/testing/test_cases_report.html
{% extends 'base.html' %}
{% load i18n %}

{% block document_title %}{{ block.super }} - {% trans 'Test Cases Report' %}{% endblock %}

{% block nav %}{% endblock %}

{% block content %}
<style type="text/css">
table.gridtable {
	font-size:11px;
	color:#333333;
	border-width: 1px;
	border-color: #666666;
	border-collapse: collapse;
}
table.gridtable th {
	border-width: 1px;
	padding: 3px;
	border-style: solid;
	border-color: #666666;
	background-color: #dedede;
}
table.gridtable td {
	border-width: 1px;
	padding: 3px;
	border-style: solid;
	border-color: #666666;
	background-color: #ffffff;
}
</style>
{% for tc in test_cases %}
	{% include 'testing/__testcase_detail.html' with table_class='gridtable' %}
<pdf:nextpage />
{% endfor %}
{% endblock %}

testing_plan/testing/templates/testing/test_cases_report_options.html
{% extends '__form.html' %}
{% load i18n %}

{% block title %}{% trans 'Test Cases Report Options' %}{% endblock %}

{% block content %}
<form method="post">
	{% csrf_token %}
	<div class="row">
		<div class="span12">
			<h3>{% trans 'Report Type' %}</h3>
			<select name="report_type">
				{% for t in report_types %}
				<option value="{{ t.0 }}">{{ t.1 }}</option>
				{% endfor %}
			</select>
		</div>
	</div>
	<div class="row">
		<div class="span12">
			<h3>{% trans 'Test Case Type' %}</h3>
			<select name="test_case_type">
				<option value="">--</option>
				{% for t in TEST_CASE_TYPES %}
				<option value="{{ t.0 }}">{{ t.1 }}</option>
				{% endfor %}
			</select>
		</div>
	</div>
	<div class="row">
		<div class="span12">
			<h3>{% trans 'Execution Type' %}</h3>
			<select name="execution_type">
				<option value="">--</option>
				{% for t in EXECUTION_TYPES %}
				<option value="{{ t.0 }}">{{ t.1 }}</option>
				{% endfor %}
			</select>
		</div>
	</div>
	<div class="row">
		<div class="span12">
			<h3>{% trans 'Only with states history' %} <input type="checkbox" name="only_with_states" /></h3>
		</div>
	</div>
	<div class="row">
		<div class="span12">
			<h3>{% trans 'Show execution results' %} <input type="checkbox" name="show_execution_results" /></h3>
		</div>
	</div>
	<input type="submit" id="submit" />
</form>
{% endblock %}

testing_plan/testing/templates/testing/testcase_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
{% with table_class="table table-bordered table-hover" %}
{% include 'testing/__testcase_detail.html' with tc=object table_class=table_class subtable_class=table_class actions=True %}
{% endwith %}
<a href="{% url 'testing:testcasestate_create' testcase_pk=object.pk %}" class="btn btn-default">{% trans "Add Test Case State" %}</a>
<a href="{% url 'testing:testcase_update' pk=object.pk %}" class="btn btn-default">{% trans "Modify" %}</a>
{% endblock %}

testing_plan/testing/templates/testing/testcasestate_confirm_delete.html
{% extends '__form.html' %}
{% load i18n %}

{% block title %}{% trans "Delete" %} {% trans "Test Case State" %}{% endblock %}

{% block content %}
<div class="alert alert-error">
	{% trans "Do you really want to delete it?" %}
</div>
{% include "testing/testcasestate_detail.html" %}
{{ block.super }}
{% endblock %}

testing_plan/testing/templates/testing/testcasestate_detail.html
{% load i18n %}
{% load user_tags %}

<h3>{% trans "State" %}</h3>
<td>{{ object.get_state_display }}</td>

<h3>{% trans "Date" %}</h3>
<td>{{ object.date }}</td>

<h3>{% trans "Corrective Action"%}</h3>
<td>{{ object.corrective_action }}</td>

<h3>{% trans "User"%}</h3>
<td>{% user_display_name object.user %}</td>

testing_plan/testing/templates/testing/testcasestate_form.html
{% extends '__form.html' %}
{% load i18n %}

{% block title_entity %}{% trans "Test Case Status" %}{% endblock %}