utene/requirements/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from requirements.views import RequirementListView, RequirementCreateView,\
    RequirementUpdateView, RequirementDeleteView


urlpatterns = patterns('testing.views',

    url(r'requirements/$', login_required(RequirementListView.as_view()), name='requirements'),
    url(r'requirement/create/$', login_required(RequirementCreateView.as_view()), name='requirement_create'),
    url(r'requirement/update/(?P<pk>\d+)/$', login_required(RequirementUpdateView.as_view()), name='requirement_update'),
    url(r'requirement/delete/(?P<pk>\d+)/$', login_required(RequirementDeleteView.as_view()), name='requirement_delete'),

)

utene/testing/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from testing.views import TestCaseListView, TestCaseCreateView, \
    TestCaseUpdateView, TestCasesReportView, TestCaseDeleteView,\
    TestCasesReportDoView, TestPlanListView, TestPlanCreateView,\
    TestPlanUpdateView, TestPlanExecutionView, TestPlanExecutionCreateView


urlpatterns = patterns('testing.views',

    url(r'test_cases/$', login_required(TestCaseListView.as_view()), name='testcases'),
    url(r'test_case/create/$', login_required(TestCaseCreateView.as_view()), name='testcase_create'),
    url(r'test_case/update/(?P<pk>\d+)/$', login_required(TestCaseUpdateView.as_view()), name='testcase_update'),
    url(r'test_case/delete/(?P<pk>\d+)/$', login_required(TestCaseDeleteView.as_view()), name='testcase_delete'),
    
    url(r'testing_plan/$', login_required(TestPlanListView.as_view()), name='testingplan'),
    url(r'testing_plan/create/$', login_required(TestPlanCreateView.as_view()), name='testplan_create'),
    url(r'testing_plan/update/(?P<pk>\d+)/$', login_required(TestPlanUpdateView.as_view()), name='testplan_update'),

    url(r'test_cases_report/$', login_required(TestCasesReportView.as_view()), name='testcasesreports'),
    url(r'test_cases_report_do/$', login_required(TestCasesReportDoView.as_view()), name='testcasesreportsdo'),
    
    url(r'testing_plan_execution/(?P<plan_pk>\d+)/$', login_required(TestPlanExecutionView.as_view()), name='testingplanexecution'),
    url(r'testing_plan_executetestcase/(?P<plan_pk>\d+)/(?P<testcase_pk>\d+)/$', login_required(TestPlanExecutionCreateView.as_view()), name='testplan_executetestcase'),

)

utene/user/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from user.views import UserInfoUpdateView


urlpatterns = patterns('user.views',

    url(r'user/(?P<pk>\d+)/$', login_required(UserInfoUpdateView.as_view()), name='userinfo'),

)

utene/utene/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required

#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
    
    url(r'^$', login_required(RedirectView.as_view(url='/requirements/requirements/')), name='home'),
    url(r'^requirements/', include('requirements.urls', namespace='requirements')),
    url(r'^testing/', include('testing.urls', namespace='testing')),
    url(r'^user/', include('user.urls', namespace='user')),
    
    #url(r'^admin/', include(admin.site.urls)),
    (r'^i18n/', include('django.conf.urls.i18n')),
    
    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html'}, name='login'),

    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',
        {'template_name': 'logout.html'}, name='logout')

)

utene/utene/forms.py
from django import forms
from django.forms.util import flatatt


class ReadOnlyWidget(forms.Widget):
    def render(self, name, value, attrs):
        final_attrs = self.build_attrs(attrs, name=name)
        if hasattr(self, 'initial'):
            value = self.initial
        return "%s" % (flatatt(final_attrs), value or '')
    
    def _has_changed(self, initial, data):
        return False


class ReadOnlyField(forms.FileField):
    widget = ReadOnlyWidget
    def __init__(self, widget=None, label=None, initial=None, help_text=None):
        forms.Field.__init__(self, label=label, initial=initial, 
            help_text=help_text, widget=widget)
    
    def clean(self, value, initial):
        self.widget.initial = initial
        return initial

utene/utene/templates/__confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<p>
	{% blocktrans %}Are you sure you want to delete "{{ object }}"? This can't be undone.{% endblocktrans %}
</p>
<form method="POST" action="{{ object.get_absolute_delete_url }}">
	{% csrf_token %}
	<button class="btn btn-danger">
		{% trans 'Yes' %}
	</button>
</form>
</div>
{% endblock %}

utene/utene/templates/__form.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
	{% if form.instance.pk %}
	{% trans 'Update' %}
	{% else %}
	{% trans 'New' %}
	{% endif %}
	{% block title_entity %}{% endblock %}
{% endblock %}

{% block content %}
	{{ block.super }}
	<form method="post" action="{% block action %}{% endblock %}">
		{% csrf_token %}
		{{ form.as_p }}
		{% block extra_form %}{% endblock %}
		<input type="submit" id="submit" />
	</form>
	{% block extra_out_form %}{% endblock %}
{% endblock %}

utene/utene/templates/__list.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% block title_entities %}{% endblock %} <a href="{% block url_new %}{% endblock %}">{% trans "New" %}</a>{% endblock %}

{% block content %}
{{ block.super }}
<table class="table">
	<tbody>
	{% for o in object_list %}
		<tr>
			<td>{{ o }}</td>
			<td><a href="{{ o.get_absolute_url }}">{% trans "Modify" %}</a></td>
		</tr>
	{% endfor %}
	</tbody>
	<tfoot>
		<tr>
			<td colspan="2">&nbsp;</td>
		</tr>
	</tfoot>
</table>
{% endblock %}

utene/utene/templates/__list_table.html
{% extends 'base.html' %}
{% load i18n %}
{% load render_table from django_tables2 %}

{% block title %}{% block title_entities %}{% endblock %} <a href="{% block url_new %}{% endblock %}">{% trans "New" %}</a>{% endblock %}

{% block content %}
{{ block.super }}
{% render_table table %}
{% endblock %}

utene/utene/templates/__record_actions.html
{% load i18n %}
<a href="{{ record.get_absolute_url }}" class="btn">{% trans "Modify" %}</a> 
<a href="{{ record.get_absolute_delete_url }}" class="btn">{% trans "Delete" %}</a>

utene/utene/templates/__record_author_user_display_name.html
{% load i18n %}
{% load user_tags %}
{% user_display_name record.author %}

utene/utene/templates/base.html
{% load i18n %}
{% load user_tags %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>{% block document_title %}Testing{% endblock %}</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.9.1.min.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.ui/jquery-ui.min.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.formset.min.js"></script>
		{% block extra_js %}{% endblock %}
		<link rel="stylesheet" media="screen" href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" media="screen" href="{{ STATIC_URL }}bootstrap/css/bootstrap-responsive.css">
		<link rel="stylesheet" media="screen" href="{{ STATIC_URL }}js/jquery.ui/themes/base/jquery-ui.min.css"  />
		<style media="screen">
			body {
				padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
			}
		</style>
	</head>
	<body>
		{% block nav %}
		<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="brand" href="{% url 'home' %}">UTENE</a>
					<div class="nav-collapse collapse">
						{% if user.is_authenticated %}
						<ul class="nav">
							<li>
								<a href="{% url 'requirements:requirements' %}">{% trans 'Requirements' %}</a>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans 'Quality' %} <b class="caret"></b></a>
								<ul class="dropdown-menu">
									<li>
										<a href="{% url 'testing:testcases' %}">{% trans 'Test Cases' %}</a>
									</li>
									<li>
										<a href="{% url 'testing:testingplan' %}">{% trans 'Testing plans' %}</a>
									</li>
									<li>
										<a href="{% url 'testing:testcasesreports' %}">{% trans 'Test Cases Report' %}</a>
									</li>
								</ul>
							</li>
						</ul>
						<ul class='nav pull-right'>
							<li class="divider-vertical"></li>
							<li>
								<form action="{% url 'set_language' %}" method="post" class="navbar-form">
									{% csrf_token %}
									<input name="next" type="hidden" value="{{ redirect_to }}" />
									<select name="language" class="input-small">
										{% get_language_info_list for LANGUAGES as languages %}
										{% for language in languages %}
										<option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}> {{ language.name_local }} ({{ language.code }}) </option>
										{% endfor %}
									</select>
									<input type="submit" value="Go" class="btn"/>
								</form>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">{% user_display_name user %} <b class="caret"></b></a>
								<ul class="dropdown-menu">
									<li>
										<a href="{% url 'user:userinfo' user.pk %}">{% trans "Profile" %}</a>
									</li>
									<li>
										<a href="{% url 'logout' %}">{% trans 'Log Out' %}</a>
									</li>
								</ul>
							</li>
						</ul>
						{% endif %}
					</div><!--/.nav-collapse -->
				</div>
			</div>
		</div>
		{% endblock %}
		<div class="container">
			<h1>{% block title %}{% endblock %}</h1>
			<h2>{% block subtitle %}{% endblock %}</h2>
			{% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				{{ message }}
			</div>
			{% endfor %}
			{% endif %}
			{% block content %}{% endblock %}
		</div>
	</body>
</html>

utene/utene/templates/login.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

{% if form.errors %}
<p>{% trans "Your username and password didn't match. Please try again." %}</p>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

utene/utene/templates/logout.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% trans 'You are logged out!' %}
{% endblock %}