utene/requirements/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from requirements.views import RequirementListView, RequirementCreateView,\
    RequirementUpdateView, RequirementDeleteView


urlpatterns = patterns('testing.views',

    url(r'requirements/$', login_required(RequirementListView.as_view()), name='requirements'),
    url(r'requirement/create/$', login_required(RequirementCreateView.as_view()), name='requirement_create'),
    url(r'requirement/update/(?P<pk>\d+)/$', login_required(RequirementUpdateView.as_view()), name='requirement_update'),
    url(r'requirement/delete/(?P<pk>\d+)/$', login_required(RequirementDeleteView.as_view()), name='requirement_delete'),

)

utene/user/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from user.views import UserInfoUpdateView


urlpatterns = patterns('user.views',

    url(r'user/(?P<pk>\d+)/$', login_required(UserInfoUpdateView.as_view()), name='userinfo'),

)

utene/utene/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required

#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
    
    url(r'^$', login_required(RedirectView.as_view(url='/requirements/requirements/')), name='home'),
    url(r'^requirements/', include('requirements.urls', namespace='requirements')),
    url(r'^testing/', include('testing.urls', namespace='testing')),
    url(r'^user/', include('user.urls', namespace='user')),
    
    #url(r'^admin/', include(admin.site.urls)),
    (r'^i18n/', include('django.conf.urls.i18n')),
    
    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html'}, name='login'),

    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout',
        {'template_name': 'logout.html'}, name='logout')

)

utene/requirements/models.py
from django.core.urlresolvers import reverse_lazy
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Requirement(models.Model):
    
    REQUIREMENT_TYPES = (
        ('FC', _('Functional')),
        ('US', _('Usability')),
        ('RE', _('Reliability')),
        ('PE', _('Performance')),
        ('SU', _('Supportability')),
        ('IM', _('(+) Implementation')),
        ('IN', _('(+) Interfaces (Not GUI)')),
        ('OP', _('(+) Operations')),
        ('EM', _('(+) Packaging')),
        ('LE', _('(+) Legals')),
    )

    type = models.CharField(verbose_name=_('Requirement Type'), 
                            max_length=2,
                            choices=REQUIREMENT_TYPES)
    name = models.CharField(verbose_name=_('Name'), max_length=255)

    def __unicode__(self):
        return u"[%s] %s" % (self.get_type_display(), self.name)
    
    def get_absolute_url(self):
        return reverse_lazy('requirements:requirement_update', 
                            kwargs={'pk': self.pk})
        
    def get_absolute_delete_url(self):
        return reverse_lazy('requirements:requirement_delete', 
                            kwargs={'pk': self.pk})

utene/requirements/forms.py
from django.forms.models import inlineformset_factory
from requirements.models import Requirement, RequirementPreCondition,\
    RequirementPostCondition, RequirementStep, RequirementAlternativePathStep,\
    RequirementAlternativePath
from django import forms


RequirementPreConditionFormSet = \
    inlineformset_factory(Requirement, RequirementPreCondition)


RequirementPostConditionFormSet = \
    inlineformset_factory(Requirement, RequirementPostCondition)


RequirementStepFormSet = \
    inlineformset_factory(Requirement, RequirementStep)


RequirementAlternativePathStepFormSet = \
    inlineformset_factory(RequirementAlternativePath, 
                          RequirementAlternativePathStep)
    

class RequirementAlternativePathForm(forms.ModelForm):
    
    class Meta:
        model = RequirementAlternativePath
        exclude = ('step', )

utene/requirements/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext as _
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django_tables2.views import SingleTableView
from requirements.models import Requirement
from requirements.tables import RequirementTable


class RequirementListView(SingleTableView):
    model = Requirement
    table_class = RequirementTable


class RequirementCreateView(CreateView):
    model = Requirement
    success_url = reverse_lazy("requirements:requirements")
    
    def form_valid(self, form):
        messages.success(self.request, _(u'Requirement created'))
        return super(RequirementCreateView, self).form_valid(form)


class RequirementUpdateView(UpdateView):
    model = Requirement
    success_url = reverse_lazy("requirements:requirements")
    
    def form_valid(self, form):
        messages.success(self.request, _(u'Requirement updated'))
        return super(RequirementUpdateView, self).form_valid(form)


class RequirementDeleteView(DeleteView):
    model = Requirement
    success_url = reverse_lazy("requirements:requirements")

utene/requirements/templates/requirements/requirement_confirm_delete.html
{% extends '__confirm_delete.html' %}

utene/requirements/templates/requirements/requirement_form.html
{% extends '__form.html' %}
{% load i18n %}

{% block title_entity %}{% trans 'Requirement' %}{% endblock %}

utene/requirements/templates/requirements/requirement_list.html
{% extends '__list_table.html' %}
{% load i18n %}

{% block title_entities %}{% trans "Requirements" %}{% endblock %}


{% block url_new %}{% url 'requirements:requirement_create' %}{% endblock %}

utene/requirements/templates/requirements/requirementalternativepath_form.html
{% extends '__form.html' %}
{% load i18n %}
{% load widget_tweaks %}

{% block title_entity %}{% trans "Alternate Path "%} for <i>{{ step }}</i>{% endblock %}

{% block extra_js %}
{{ block.super }}
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.flexibleArea.js"></script>
<script>
	$(document).ready(function(){
		$('#steps tbody tr').formset({
			prefix: '{{ preconditions_formset.prefix }}',
			addText: '{% trans "add another" %}',
			deleteText: '{% trans "remove" %}'
		});
	});
</script>
{% endblock %}

{% block extra_form %}
<h3>{% trans "Steps" %}</h3>
<div>
	{{ formset.management_form }}
	{{ formset.non_form_errors }}
	<table id="steps" class='table table-condensed'>
		<thead>
			{% with formset.forms|first as pc %}
			<tr>
				<td>{{ pc.step_number.label }}</td>
				<td>{{ pc.description.label }}</td>
				<td>{{ pc.DELETE.label }}</td>
			</tr>
			{% endwith %}
		</thead>
		<tbody>
			{% for subform in formset.forms %}
			<tr>
				<td>{% render_field subform.step_number class+='span1' %}{{ subform.step_number.errors }}</td>
				<td>{% render_field subform.description class+='span5' rows=3 %}{{ subform.description.errors }}</td>
				<td>
					{{ subform.DELETE }}{{ subform.DELETE.errors }}
					{% for h in subform.hidden_fields %}
					{{ h }}
					{% endfor %}
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% endblock %}